"""Cloud entrypoint, portable path, and read-only deployment tests."""

from __future__ import annotations

import hashlib
import runpy
import tomllib
from pathlib import Path

from streamlit.testing.v1 import AppTest

from arxiv_digest.dashboard.data import DashboardDataError, load_digest, load_digest_history
from arxiv_digest.dashboard.paths import find_repository_root, resolve_dashboard_paths

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_root_entrypoint_imports_without_starting_streamlit() -> None:
    namespace = runpy.run_path(str(REPOSITORY_ROOT / "streamlit_app.py"), run_name="cloud_import")
    assert namespace["main"].__module__ == "arxiv_digest.dashboard.app"


def test_repository_root_discovery_and_paths_do_not_depend_on_cwd(
    monkeypatch, tmp_path: Path
) -> None:  # type: ignore[no-untyped-def]
    monkeypatch.chdir(tmp_path)
    assert find_repository_root(REPOSITORY_ROOT / "src" / "arxiv_digest" / "dashboard") == (
        REPOSITORY_ROOT
    )
    paths = resolve_dashboard_paths(repository_root=REPOSITORY_ROOT)
    assert paths.report == (REPOSITORY_ROOT / "reports" / "latest.json").resolve()
    assert paths.reports_dir == (REPOSITORY_ROOT / "reports").resolve()


def test_path_overrides_are_portable_and_root_relative(tmp_path: Path) -> None:
    relative = resolve_dashboard_paths(
        repository_root=tmp_path,
        report=Path("reports/archive/latest.json"),
        reports_dir=Path("reports/archive"),
    )
    assert relative.report == (tmp_path / "reports" / "archive" / "latest.json").resolve()
    assert relative.report.as_posix().endswith("/reports/archive/latest.json")
    absolute_report = (tmp_path / "outside" / "digest.json").resolve()
    absolute = resolve_dashboard_paths(
        repository_root=REPOSITORY_ROOT,
        report=absolute_report,
        reports_dir=tmp_path,
    )
    assert absolute.report == absolute_report
    assert absolute.reports_dir == tmp_path.resolve()


def test_repository_root_failure_is_actionable(tmp_path: Path) -> None:
    try:
        find_repository_root(tmp_path)
    except DashboardDataError as exc:
        assert "complete checkout" in str(exc)
    else:
        raise AssertionError("An incomplete checkout must not resolve as a repository root")


def test_committed_reports_load_latest_and_history_without_writes() -> None:
    reports_dir = REPOSITORY_ROOT / "reports"
    latest = reports_dir / "latest.json"
    dated = reports_dir / "2026-07-29-weekly-arxiv-digest.json"
    before = {path: (_sha256(path), path.stat().st_mtime_ns) for path in (latest, dated)}
    digest = load_digest(latest)
    history, errors = load_digest_history(reports_dir)
    after = {path: (_sha256(path), path.stat().st_mtime_ns) for path in (latest, dated)}
    assert digest.schema_version == "1.0"
    assert any(entry.path == dated for entry, _digest in history)
    assert errors == []
    assert after == before


def test_cloud_entrypoint_renders_notice_and_uses_committed_latest() -> None:
    test_app = AppTest.from_file(str(REPOSITORY_ROOT / "streamlit_app.py"), default_timeout=20)
    test_app.run()
    assert not test_app.exception
    assert any("Personalized Weekly" in title.value for title in test_app.title)
    assert any(
        caption.value
        == "Read-only dashboard. Reports are generated by the scheduled digest workflow."
        for caption in test_app.sidebar.caption
    )


def test_cloud_dependency_and_configuration_have_one_authoritative_source() -> None:
    pyproject = tomllib.loads((REPOSITORY_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    dependencies = pyproject["project"]["dependencies"]
    assert len([value for value in dependencies if value.startswith("streamlit")]) == 1
    assert "optional-dependencies" not in pyproject["project"]
    assert (REPOSITORY_ROOT / "uv.lock").is_file()
    assert not (REPOSITORY_ROOT / "requirements.txt").exists()
    config = tomllib.loads(
        (REPOSITORY_ROOT / ".streamlit" / "config.toml").read_text(encoding="utf-8")
    )
    assert config["server"]["headless"] is True
    assert "address" not in config["server"]
    assert "serverAddress" not in config["browser"]
